import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import "../globals.css";
import { makeStore } from "@/utils/store";
import { Provider } from "react-redux";
import ReduxProvider from "@/app/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`min-h-full bg-gray-50 text-gray-900 ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          {/* Header with Navbar */}
          <header className="shadow-md">
            <Navbar />
          </header>

          {/* Main Content */}
          <main className="relative flex flex-col items-center justify-center mx-auto max-w-[1240px] py-6 px-4 sm:px-6 mt-20 lg:px-8">
            {children}
          </main>

          {/* Footer */}
          <footer className="mt-auto bg-gray-800 text-gray-300">
            <div className="max-w-[1240px] mx-auto p-4 text-center">
              <p className="text-sm">
                Built with <span className="text-red-500">&hearts;</span> by
                Your Name
              </p>
            </div>
          </footer>
        </ReduxProvider>
      </body>
    </html>
  );
}
